name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checa o código do repositório
    - name: Checkout code
      uses: actions/checkout@v3

    # Configura a versão do Java
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    # Configura o cache para acelerar o build
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Instala dependências e executa os testes
    - name: Build with Maven
      run: mvn clean install

    # Gera relatório de cobertura com JaCoCo
    - name: Run JaCoCo Test Coverage Report
      run: mvn verify

    # Publica os relatórios gerados como artefatos (opcional)
    - name: Upload Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: jacoco-report
        path: target/site/jacoco/index.html
